/**
 * MOOSIC AUTHENTIC CATALOG REGISTRY
 * 
 * Registro curado e verificado de metadados oficiais e de altíssima resolução (1000x1000bb / 600x600bb)
 * para os maiores artistas, álbuns e referências da música brasileira e internacional.
 */

export interface AuthenticArtistInfo {
  id: string;
  name: string;
  normalizedNames: string[];
  avatarUrl: string;
  bannerUrl?: string;
  genre: string;
  monthlyListeners: string;
  bio: string;
  origin: string;
  verified: boolean;
  featuredTrackTitle?: string;
  topAlbums?: string[];
}

export interface AuthenticAlbumInfo {
  id: string;
  title: string;
  normalizedTitles: string[];
  artistName: string;
  coverUrl: string;
  releaseYear: number;
  label: string;
  genre: string;
  totalTracks: number;
  hiResBadge: string;
}

export const AUTHENTIC_ARTISTS: Record<string, AuthenticArtistInfo> = {
  matue: {
    id: 'matue',
    name: 'Matuê',
    normalizedNames: ['matue', 'matue 30praum', 'matue oficial', 'matheo brasileiro'],
    avatarUrl: 'https://cdn-images.dzcdn.net/images/artist/c42fcb920963cca4d195b939e51f19d1/1000x1000-000000-80-0-0.jpg',
    bannerUrl: 'https://cdn-images.dzcdn.net/images/artist/c42fcb920963cca4d195b939e51f19d1/1000x1000-000000-80-0-0.jpg',
    genre: 'Trap Brasil / Hip-Hop',
    monthlyListeners: '8.4M ouvintes mensais',
    bio: 'Matheus Brasileiro Aguiar, artisticamente conhecido como Matuê, é pioneiro do trap nacional e fundador do selo 30PRAUM. Conhecido por quebrar recordes no streaming com álbuns icônicos como Máquina do Tempo e 333.',
    origin: 'Fortaleza, CE - Brasil',
    verified: true,
    featuredTrackTitle: 'Máquina do Tempo',
    topAlbums: ['333', 'Máquina do Tempo', 'Sabor Overdose no Prato'],
  },

  the_weeknd: {
    id: 'the_weeknd',
    name: 'The Weeknd',
    normalizedNames: ['the weeknd', 'the weekend', 'abel tesfaye', 'theweeknd', 'abel makkonen tesfaye'],
    avatarUrl: 'https://cdn-images.dzcdn.net/images/artist/581693b4724a7fcfa754455101e13a44/1000x1000-000000-80-0-0.jpg',
    bannerUrl: 'https://cdn-images.dzcdn.net/images/artist/581693b4724a7fcfa754455101e13a44/1000x1000-000000-80-0-0.jpg',
    genre: 'R&B Contemporâneo / Synthpop',
    monthlyListeners: '112.5M ouvintes mensais',
    bio: 'Abel Makkonen Tesfaye, conhecido como The Weeknd, é um dos maiores artistas globais do século XXI. Suas narrativas cinematográficas e produção synthwave moldaram a estética do pop moderno com After Hours, Starboy e Dawn FM.',
    origin: 'Toronto - Canadá',
    verified: true,
    featuredTrackTitle: 'Blinding Lights',
    topAlbums: ['After Hours', 'Starboy', 'Dawn FM', 'Beauty Behind the Madness'],
  },

  bk: {
    id: 'bk',
    name: "BK'",
    normalizedNames: ['bk', "bk'", 'abebe bikila', 'bk’', 'bk rap'],
    avatarUrl: 'https://cdn-images.dzcdn.net/images/artist/7481fc25e9bf8f0d8c416ecb9104927d/1000x1000-000000-80-0-0.jpg',
    bannerUrl: 'https://cdn-images.dzcdn.net/images/artist/7481fc25e9bf8f0d8c416ecb9104927d/1000x1000-000000-80-0-0.jpg',
    genre: 'Rap Nacional / Lírica Urbana',
    monthlyListeners: '3.6M ouvintes mensais',
    bio: "Abebe Bikila, o BK', é uma das maiores vozes da poesia e lirismo do hip-hop brasileiro contemporâneo. Autor de clássicos reverenciados como Castelos & Ruínas, Gigantes e o consagrado projeto conceitual ICARUS.",
    origin: 'Rio de Janeiro, RJ - Brasil',
    verified: true,
    featuredTrackTitle: 'Planos',
    topAlbums: ['ICARUS', 'Castelos & Ruínas', 'Gigantes', 'O Líder em Movimento'],
  },

  dua_lipa: {
    id: 'dua_lipa',
    name: 'Dua Lipa',
    normalizedNames: ['dua lipa', 'dualipa'],
    avatarUrl: 'https://cdn-images.dzcdn.net/images/artist/877872aaf75694f11d53c318700ab2b5/1000x1000-000000-80-0-0.jpg',
    bannerUrl: 'https://cdn-images.dzcdn.net/images/artist/877872aaf75694f11d53c318700ab2b5/1000x1000-000000-80-0-0.jpg',
    genre: 'Disco Pop / Dance-Pop',
    monthlyListeners: '68.3M ouvintes mensais',
    bio: 'Cantora e compositora britânica de ascendência albanesa, vencedora de múltiplos Grammys. Reinventou a era nu-disco com o aclamado álbum Future Nostalgia e seguiu inovando em Radical Optimism.',
    origin: 'Londres - Reino Unido',
    verified: true,
    featuredTrackTitle: 'Levitating',
    topAlbums: ['Future Nostalgia', 'Radical Optimism', 'Dua Lipa (Complete Edition)'],
  },

  djonga: {
    id: 'djonga',
    name: 'Djonga',
    normalizedNames: ['djonga', 'gustavo djonga', 'djonga oficial'],
    avatarUrl: 'https://cdn-images.dzcdn.net/images/artist/a685bd7ab1fd1234b7b420c59ca5be4f/1000x1000-000000-80-0-0.jpg',
    bannerUrl: 'https://cdn-images.dzcdn.net/images/artist/a685bd7ab1fd1234b7b420c59ca5be4f/1000x1000-000000-80-0-0.jpg',
    genre: 'Rap Nacional / Hardcore Hip-Hop',
    monthlyListeners: '4.2M ouvintes mensais',
    bio: 'Gustavo Pereira Neves, o Djonga, é um dos mais influentes e contundentes rappers do Brasil. Conhecido por lançamentos anuais marcantes como Heresia, O Menino que Queria Ser Deus, Ladrão e O Dono do Lugar.',
    origin: 'Belo Horizonte, MG - Brasil',
    verified: true,
    featuredTrackTitle: 'Leal',
    topAlbums: ['Ladrão', 'Heresia', 'O Menino que Queria Ser Deus', 'O Dono do Lugar'],
  },

  sabotage: {
    id: 'sabotage',
    name: 'Sabotage',
    normalizedNames: ['sabotage', 'mauro mateus', 'maestro do canao', 'sabotage oficial'],
    avatarUrl: 'https://cdn-images.dzcdn.net/images/artist/6bc5df6e162a2cd889922ff1f6350f5c/1000x1000-000000-80-0-0.jpg',
    bannerUrl: 'https://cdn-images.dzcdn.net/images/artist/6bc5df6e162a2cd889922ff1f6350f5c/1000x1000-000000-80-0-0.jpg',
    genre: 'Rap Nacional / Clássico & Patrimônio',
    monthlyListeners: '1.8M ouvintes mensais',
    bio: 'Mauro Mateus dos Santos, o eterno Maestro do Canão. Um dos maiores gênios líricos e rítmicos da história da música brasileira, cujo legado imortal em Rap É Compromisso definiu gerações.',
    origin: 'São Paulo, SP - Brasil',
    verified: true,
    featuredTrackTitle: 'Um Bom Lugar',
    topAlbums: ['Rap É Compromisso', 'Sabotage (Álbum Póstumo)'],
  },

  racionais_mcs: {
    id: 'racionais_mcs',
    name: "Racionais MC's",
    normalizedNames: ['racionais', "racionais mc's", 'racionais mcs', 'mano brown', 'ice blue', 'edi rock', 'kl jay'],
    avatarUrl: 'https://cdn-images.dzcdn.net/images/artist/eb2451cb8d2eefe925a8ecffc8ff5e55/1000x1000-000000-80-0-0.jpg',
    bannerUrl: 'https://cdn-images.dzcdn.net/images/artist/eb2451cb8d2eefe925a8ecffc8ff5e55/1000x1000-000000-80-0-0.jpg',
    genre: 'Rap Nacional / Crônica Social',
    monthlyListeners: '5.1M ouvintes mensais',
    bio: "Formado em 1988 por Mano Brown, Ice Blue, Edi Rock e KL Jay, o grupo Racionais MC's é o maior expoente cultural do rap brasileiro, autor de obras-primas fundamentais como Sobrevivendo no Inferno e Nada Como um Dia após o Outro Dia.",
    origin: 'São Paulo, SP - Brasil',
    verified: true,
    featuredTrackTitle: 'Vida Loka (Pt. 1)',
    topAlbums: ['Sobrevivendo no Inferno', 'Nada como um Dia após o Outro Dia', 'Cores & Valores'],
  },

  criolo: {
    id: 'criolo',
    name: 'Criolo',
    normalizedNames: ['criolo', 'criolo doido', 'kleber cavalcante gomes'],
    avatarUrl: 'https://cdn-images.dzcdn.net/images/artist/9c4d6b91bbb37c2a9197eb8a6a3848be/1000x1000-000000-80-0-0.jpg',
    bannerUrl: 'https://cdn-images.dzcdn.net/images/artist/9c4d6b91bbb37c2a9197eb8a6a3848be/1000x1000-000000-80-0-0.jpg',
    genre: 'MPB / Rap / Samba',
    monthlyListeners: '2.3M ouvintes mensais',
    bio: 'Cantor, compositor e rapper paulistano aclamado internacionalmente por mesclar rap, samba, afrobeat e MPB em discos como Nó na Orelha, Convoque Seu Buda, Espiral de Ilusão e Sobre Viver.',
    origin: 'São Paulo, SP - Brasil',
    verified: true,
    featuredTrackTitle: 'Não Existe Amor em SP',
    topAlbums: ['Nó na Orelha', 'Convoque Seu Buda', 'Espiral de Ilusão', 'Sobre Viver'],
  },

  daft_punk: {
    id: 'daft_punk',
    name: 'Daft Punk',
    normalizedNames: ['daft punk', 'thomas bangalter', 'guy manuel', 'daftpunk'],
    avatarUrl: 'https://cdn-images.dzcdn.net/images/artist/638e69b9caaf9f9f3f8826febea7b543/1000x1000-000000-80-0-0.jpg',
    bannerUrl: 'https://cdn-images.dzcdn.net/images/artist/638e69b9caaf9f9f3f8826febea7b543/1000x1000-000000-80-0-0.jpg',
    genre: 'Electronic / French House / Synthpop',
    monthlyListeners: '23.8M ouvintes mensais',
    bio: 'Lendário duo francês formado por Thomas Bangalter e Guy-Manuel de Homem-Christo. Revolucionaram a música eletrônica mundial através de Homework, Discovery, Human After All e o monumental Random Access Memories.',
    origin: 'Paris - França',
    verified: true,
    featuredTrackTitle: 'Instant Crush',
    topAlbums: ['Random Access Memories', 'Discovery', 'Homework', 'Alive 2007'],
  },

  frank_ocean: {
    id: 'frank_ocean',
    name: 'Frank Ocean',
    normalizedNames: ['frank ocean', 'christopher breaux', 'lonny breaux', 'frankocean'],
    avatarUrl: 'https://cdn-images.dzcdn.net/images/artist/882155c08dc31d6464d6d580083c968c/1000x1000-000000-80-0-0.jpg',
    bannerUrl: 'https://cdn-images.dzcdn.net/images/artist/882155c08dc31d6464d6d580083c968c/1000x1000-000000-80-0-0.jpg',
    genre: 'Alternative R&B / Neo-Soul',
    monthlyListeners: '35.4M ouvintes mensais',
    bio: 'Compositor e cantor norte-americano cultuado mundialmente por suas harmonias introspectivas e vanguarda sonora demonstradas nos clássicos imortais Channel Orange e Blonde.',
    origin: 'Nova Orleans, LA - EUA',
    verified: true,
    featuredTrackTitle: 'Pink + White',
    topAlbums: ['Blonde', 'Channel Orange', 'Nostalgia, Ultra', 'Endless'],
  },

  lofi_girl: {
    id: 'lofi_girl',
    name: 'Lofi Girl',
    normalizedNames: ['lofi girl', 'chilledcow', 'lofi beats', 'lofi hip hop', 'lofigirl'],
    avatarUrl: 'https://cdn-images.dzcdn.net/images/artist/f5c07c0a901f819f11d8a69b8e8da119/1000x1000-000000-80-0-0.jpg',
    bannerUrl: 'https://cdn-images.dzcdn.net/images/artist/f5c07c0a901f819f11d8a69b8e8da119/1000x1000-000000-80-0-0.jpg',
    genre: 'Chillhop / Lo-Fi Beats / Study Flow',
    monthlyListeners: '14.2M ouvintes mensais',
    bio: 'O maior hub global de música lo-fi e relaxamento sonoro. Frequências orgânicas e batidas suaves que acompanham milhões de estudantes e criadores 24 horas por dia.',
    origin: 'Paris - França',
    verified: true,
    featuredTrackTitle: 'Study Beats',
    topAlbums: ['Morning Coffee', 'Midnight Study', 'Cozy Winter', 'Lofi Sleep'],
  },

  teto: {
    id: 'teto',
    name: 'Teto',
    normalizedNames: ['teto', 'teto 30praum', 'cleiton teto'],
    avatarUrl: 'https://cdn-images.dzcdn.net/images/artist/ef01e9000762e97eef6ba01955f0073c/1000x1000-000000-80-0-0.jpg',
    bannerUrl: 'https://cdn-images.dzcdn.net/images/artist/ef01e9000762e97eef6ba01955f0073c/1000x1000-000000-80-0-0.jpg',
    genre: 'Trap Brasil / Melodic Trap',
    monthlyListeners: '6.5M ouvintes mensais',
    bio: 'Revelação do trap nacional e integrante de destaque da 30PRAUM, famoso por sucessos como Minha Vida É Um Filme, M4 feat. Matuê, Mustang Preto e Manha.',
    origin: 'Jacobina, BA - Brasil',
    verified: true,
    featuredTrackTitle: 'Minha Vida É Um Filme',
    topAlbums: ['Prévia', 'Minha Vida É Um Filme'],
  },

  wiu: {
    id: 'wiu',
    name: 'WIU',
    normalizedNames: ['wiu', 'wiu 30praum', 'vinicius wiu'],
    avatarUrl: 'https://cdn-images.dzcdn.net/images/artist/33c57e62925f8aa9639ede9c92a198d8/1000x1000-000000-80-0-0.jpg',
    bannerUrl: 'https://cdn-images.dzcdn.net/images/artist/33c57e62925f8aa9639ede9c92a198d8/1000x1000-000000-80-0-0.jpg',
    genre: 'Trap Brasil / Autotune R&B',
    monthlyListeners: '6.1M ouvintes mensais',
    bio: 'Produtor musical e cantor cearense, arquiteto sonoro de diversos hits nacionais e autor do álbum de sucesso Manual de Como Amar Errado.',
    origin: 'Fortaleza, CE - Brasil',
    verified: true,
    featuredTrackTitle: 'Coração de Gelo',
    topAlbums: ['Manual de Como Amar Errado', 'Vagabundo de Luxo'],
  },

  veigh: {
    id: 'veigh',
    name: 'Veigh',
    normalizedNames: ['veigh', 'thiago veigh'],
    avatarUrl: 'https://cdn-images.dzcdn.net/images/artist/c93bd826c5af54c29881c5928a36c82d/1000x1000-000000-80-0-0.jpg',
    bannerUrl: 'https://cdn-images.dzcdn.net/images/artist/c93bd826c5af54c29881c5928a36c82d/1000x1000-000000-80-0-0.jpg',
    genre: 'Trap Brasil / R&B Urbano',
    monthlyListeners: '8.9M ouvintes mensais',
    bio: 'Um dos maiores fenômenos do streaming nacional com o álbum Dos Prédios Deluxe, alcançando o Top Global com faixas como Novo Balanço e Engana Dizendo Que Ama.',
    origin: 'Itapevi, SP - Brasil',
    verified: true,
    featuredTrackTitle: 'Novo Balanço',
    topAlbums: ['Dos Prédios', 'Dos Prédios Deluxe'],
  },

  kayblack: {
    id: 'kayblack',
    name: 'KayBlack',
    normalizedNames: ['kayblack', 'kay black'],
    avatarUrl: 'https://cdn-images.dzcdn.net/images/artist/b2594f37faef22fd11fa356d23944e95/1000x1000-000000-80-0-0.jpg',
    bannerUrl: 'https://cdn-images.dzcdn.net/images/artist/b2594f37faef22fd11fa356d23944e95/1000x1000-000000-80-0-0.jpg',
    genre: 'Trap / Funk / R&B Urbano',
    monthlyListeners: '7.2M ouvintes mensais',
    bio: 'Cantor e compositor paulista conhecido pelo timbre marcante e letras confessionais sobre superação, amor e vivência no EP Contradições.',
    origin: 'São Paulo, SP - Brasil',
    verified: true,
    featuredTrackTitle: 'Segredo',
    topAlbums: ['Contradições'],
  },

  filipe_ret: {
    id: 'filipe_ret',
    name: 'Filipe Ret',
    normalizedNames: ['filipe ret', 'ret', 'filiperet'],
    avatarUrl: 'https://cdn-images.dzcdn.net/images/artist/3eee3f3d5974909de588b4096f58f766/1000x1000-000000-80-0-0.jpg',
    bannerUrl: 'https://cdn-images.dzcdn.net/images/artist/3eee3f3d5974909de588b4096f58f766/1000x1000-000000-80-0-0.jpg',
    genre: 'Trap / Rap Nacional',
    monthlyListeners: '8.1M ouvintes mensais',
    bio: 'Ícone do rap e trap carioca, fundador da NadaMal e autor de clássicos atemporais como Vivaz, Revel, Audaz, Imaterial e LUME.',
    origin: 'Rio de Janeiro, RJ - Brasil',
    verified: true,
    featuredTrackTitle: 'Melhor Agora',
    topAlbums: ['LUME', 'Imaterial', 'Audaz', 'Vivaz'],
  },

  mc_cabelinho: {
    id: 'mc_cabelinho',
    name: 'MC Cabelinho',
    normalizedNames: ['mc cabelinho', 'cabelinho', 'victor hugo'],
    avatarUrl: 'https://cdn-images.dzcdn.net/images/artist/9af42c5b0cecdd05765ec8a7f568d3af/1000x1000-000000-80-0-0.jpg',
    bannerUrl: 'https://cdn-images.dzcdn.net/images/artist/9af42c5b0cecdd05765ec8a7f568d3af/1000x1000-000000-80-0-0.jpg',
    genre: 'Trap / Funk Carioca / R&B',
    monthlyListeners: '7.8M ouvintes mensais',
    bio: 'Expoente da união entre o trap e o funk carioca, autor de álbuns aclamados como LITTLE LOVE e LITTLE LOVE DELUXE.',
    origin: 'Rio de Janeiro, RJ - Brasil',
    verified: true,
    featuredTrackTitle: 'Minha Cura',
    topAlbums: ['LITTLE LOVE', 'LITTLE LOVE DELUXE', 'Ainda'],
  },

  orochi: {
    id: 'orochi',
    name: 'Orochi',
    normalizedNames: ['orochi', 'flavio cesar orochi', 'orochi mainstreet'],
    avatarUrl: 'https://cdn-images.dzcdn.net/images/artist/273be20213124429a86ed2b0325b3780/1000x1000-000000-80-0-0.jpg',
    bannerUrl: 'https://cdn-images.dzcdn.net/images/artist/273be20213124429a86ed2b0325b3780/1000x1000-000000-80-0-0.jpg',
    genre: 'Trap Brasil / Mainstreet',
    monthlyListeners: '6.9M ouvintes mensais',
    bio: 'Campeão nacional de batalhas de rima e fundador da Mainstreet Records. Líder nas paradas com Celebridade, Lobo e Vida Cara.',
    origin: 'São Gonçalo, RJ - Brasil',
    verified: true,
    featuredTrackTitle: 'Amor de Fim de Noite',
    topAlbums: ['Vida Cara', 'Lobo', 'Celebridade'],
  },

  caetano_veloso: {
    id: 'caetano_veloso',
    name: 'Caetano Veloso',
    normalizedNames: ['caetano veloso', 'caetano', 'caetanoveloso'],
    avatarUrl: 'https://cdn-images.dzcdn.net/images/artist/466d6b39a0b650f29c961a949de0fac4/1000x1000-000000-80-0-0.jpg',
    bannerUrl: 'https://cdn-images.dzcdn.net/images/artist/466d6b39a0b650f29c961a949de0fac4/1000x1000-000000-80-0-0.jpg',
    genre: 'MPB / Tropicália / Vanguarda',
    monthlyListeners: '4.8M ouvintes mensais',
    bio: 'Um dos maiores músicos e pensadores da história do Brasil, líder do movimento Tropicalista e compositor de obras monumentais como Transa, Muito, Estrangeiro e Meu Coco.',
    origin: 'Santo Amaro, BA - Brasil',
    verified: true,
    featuredTrackTitle: 'Você é Linda',
    topAlbums: ['Transa', 'Tropicália', 'Estrangeiro', 'Meu Coco'],
  },

  tim_maia: {
    id: 'tim_maia',
    name: 'Tim Maia',
    normalizedNames: ['tim maia', 'sebastiao rodrigues maia', 'timmaia'],
    avatarUrl: 'https://cdn-images.dzcdn.net/images/artist/fa32f3688e3b5901b7588020b0377623/1000x1000-000000-80-0-0.jpg',
    bannerUrl: 'https://cdn-images.dzcdn.net/images/artist/fa32f3688e3b5901b7588020b0377623/1000x1000-000000-80-0-0.jpg',
    genre: 'Soul Brasileiro / Funk / MPB',
    monthlyListeners: '3.9M ouvintes mensais',
    bio: 'O Síndico da música brasileira. Trouxe o soul e o funk norte-americano para o Brasil com uma potência vocal inigualável nos álbuns Racional Vol. 1 & 2 e O Descobridor dos Sete Mares.',
    origin: 'Rio de Janeiro, RJ - Brasil',
    verified: true,
    featuredTrackTitle: 'Não Quero Dinheiro (Só Quero Amar)',
    topAlbums: ['Tim Maia Racional Vol. 1', 'O Descobridor dos Sete Mares', 'Tim Maia 1970'],
  },

  liniker: {
    id: 'liniker',
    name: 'Liniker',
    normalizedNames: ['liniker', 'liniker oficial'],
    avatarUrl: 'https://cdn-images.dzcdn.net/images/artist/efbdafb9814553cec3f2898e85199f11/1000x1000-000000-80-0-0.jpg',
    bannerUrl: 'https://cdn-images.dzcdn.net/images/artist/efbdafb9814553cec3f2898e85199f11/1000x1000-000000-80-0-0.jpg',
    genre: 'MPB / Soul Brasileiro / Samba',
    monthlyListeners: '3.8M ouvintes mensais',
    bio: 'Cantora e compositora brasileira vencedora do Grammy Latino. Autora de álbuns históricos como Indigo Borboleta Anil e CAJU.',
    origin: 'Araraquara, SP - Brasil',
    verified: true,
    featuredTrackTitle: 'Caju',
    topAlbums: ['CAJU', 'Indigo Borboleta Anil'],
  },

  travis_scott: {
    id: 'travis_scott',
    name: 'Travis Scott',
    normalizedNames: ['travis scott', 'jacques webster', 'la flame', 'travisscott'],
    avatarUrl: 'https://cdn-images.dzcdn.net/images/artist/8d8316146026d7e6ce377e314536df62/1000x1000-000000-80-0-0.jpg',
    bannerUrl: 'https://cdn-images.dzcdn.net/images/artist/8d8316146026d7e6ce377e314536df62/1000x1000-000000-80-0-0.jpg',
    genre: 'Trap / Hip-Hop Psicodélico',
    monthlyListeners: '74.2M ouvintes mensais',
    bio: 'Rapper, produtor e ícone cultural norte-americano, visionário por trás de projetos imersivos como ASTROWORLD, Rodeo e UTOPIA.',
    origin: 'Houston, TX - EUA',
    verified: true,
    featuredTrackTitle: 'FE!N',
    topAlbums: ['UTOPIA', 'ASTROWORLD', 'Rodeo', 'Birds in the Trap Sing McKnight'],
  },

  kendrick_lamar: {
    id: 'kendrick_lamar',
    name: 'Kendrick Lamar',
    normalizedNames: ['kendrick lamar', 'k dot', 'kung fu kenny', 'kendricklamar'],
    avatarUrl: 'https://cdn-images.dzcdn.net/images/artist/be0a7c550567f4af0ed202d7235b74d6/1000x1000-000000-80-0-0.jpg',
    bannerUrl: 'https://cdn-images.dzcdn.net/images/artist/be0a7c550567f4af0ed202d7235b74d6/1000x1000-000000-80-0-0.jpg',
    genre: 'Conscious Hip-Hop / West Coast',
    monthlyListeners: '65.8M ouvintes mensais',
    bio: 'Ganhador do Prêmio Pulitzer e de múltiplos Grammys, considerado uma das maiores vozes do hip-hop de todos os tempos por To Pimp a Butterfly, good kid, m.A.A.d city, DAMN. e GNX.',
    origin: 'Compton, CA - EUA',
    verified: true,
    featuredTrackTitle: 'Not Like Us',
    topAlbums: ['DAMN.', 'good kid, m.A.A.d city', 'To Pimp a Butterfly', 'GNX'],
  },

  billie_eilish: {
    id: 'billie_eilish',
    name: 'Billie Eilish',
    normalizedNames: ['billie eilish', 'billie', 'billieeilish'],
    avatarUrl: 'https://cdn-images.dzcdn.net/images/artist/8eab1a9a644889aabaca1e193e05f984/1000x1000-000000-80-0-0.jpg',
    bannerUrl: 'https://cdn-images.dzcdn.net/images/artist/8eab1a9a644889aabaca1e193e05f984/1000x1000-000000-80-0-0.jpg',
    genre: 'Alt-Pop / Indie Pop / Dark Wave',
    monthlyListeners: '98.6M ouvintes mensais',
    bio: 'Compositora e cantora norte-americana que redefiniu o pop moderno com seu estilo intimista e produção inovadora em WHEN WE ALL FALL ASLEEP, WHERE DO WE GO? e HIT ME HARD AND SOFT.',
    origin: 'Los Angeles, CA - EUA',
    verified: true,
    featuredTrackTitle: 'BIRDS OF A FEATHER',
    topAlbums: ['HIT ME HARD AND SOFT', 'Happier Than Ever', 'WHEN WE ALL FALL ASLEEP...'],
  },

  arctic_monkeys: {
    id: 'arctic_monkeys',
    name: 'Arctic Monkeys',
    normalizedNames: ['arctic monkeys', 'alex turner', 'arcticmonkeys'],
    avatarUrl: 'https://cdn-images.dzcdn.net/images/artist/6c03e4c7c36800897fd468633286db24/1000x1000-000000-80-0-0.jpg',
    bannerUrl: 'https://cdn-images.dzcdn.net/images/artist/6c03e4c7c36800897fd468633286db24/1000x1000-000000-80-0-0.jpg',
    genre: 'Indie Rock / Post-Punk Revival',
    monthlyListeners: '48.5M ouvintes mensais',
    bio: 'Banda britânica de rock formada em Sheffield, liderada por Alex Turner. Marcaram a era digital com AM, Whatever People Say I Am e Favourite Worst Nightmare.',
    origin: 'Sheffield - Reino Unido',
    verified: true,
    featuredTrackTitle: 'Do I Wanna Know?',
    topAlbums: ['AM', 'Favourite Worst Nightmare', 'The Car'],
  },

  tame_impala: {
    id: 'tame_impala',
    name: 'Tame Impala',
    normalizedNames: ['tame impala', 'kevin parker', 'tameimpala'],
    avatarUrl: 'https://cdn-images.dzcdn.net/images/artist/879015e713cc6ad6ffaeec154c027505/1000x1000-000000-80-0-0.jpg',
    bannerUrl: 'https://cdn-images.dzcdn.net/images/artist/879015e713cc6ad6ffaeec154c027505/1000x1000-000000-80-0-0.jpg',
    genre: 'Psychedelic Pop / Synth-Pop',
    monthlyListeners: '32.1M ouvintes mensais',
    bio: 'Projeto psicodélico e visionário do multi-instrumentista australiano Kevin Parker. Criador dos clássicos imortais Currents, The Slow Rush e Lonerism.',
    origin: 'Perth - Austrália',
    verified: true,
    featuredTrackTitle: 'The Less I Know The Better',
    topAlbums: ['Currents', 'The Slow Rush', 'Lonerism'],
  },

  sza: {
    id: 'sza',
    name: 'SZA',
    normalizedNames: ['sza', 'solana rowe', 'sza oficial'],
    avatarUrl: 'https://cdn-images.dzcdn.net/images/artist/8ced041da2bed70d5715f0860956169b/1000x1000-000000-80-0-0.jpg',
    bannerUrl: 'https://cdn-images.dzcdn.net/images/artist/8ced041da2bed70d5715f0860956169b/1000x1000-000000-80-0-0.jpg',
    genre: 'R&B Contemporâneo / Neo-Soul',
    monthlyListeners: '72.4M ouvintes mensais',
    bio: 'Cantora e compositora norte-americana da TDE. Líder global com os álbuns revolucionários Ctrl e SOS.',
    origin: 'St. Louis, MO - EUA',
    verified: true,
    featuredTrackTitle: 'Kill Bill',
    topAlbums: ['SOS', 'Ctrl', 'Lana'],
  },

  queen: {
    id: 'queen',
    name: 'Queen',
    normalizedNames: ['queen', 'freddie mercury', 'brian may', 'queen oficial'],
    avatarUrl: 'https://cdn-images.dzcdn.net/images/artist/a131ced363dd67249e6a9167164188cb/1000x1000-000000-80-0-0.jpg',
    bannerUrl: 'https://cdn-images.dzcdn.net/images/artist/a131ced363dd67249e6a9167164188cb/1000x1000-000000-80-0-0.jpg',
    genre: 'Classic Rock / Progressive Rock',
    monthlyListeners: '51.3M ouvintes mensais',
    bio: 'Lendária banda britânica liderada por Freddie Mercury, autora dos maiores hinos da história da música como Bohemian Rhapsody, Don\'t Stop Me Now e We Will Rock You.',
    origin: 'Londres - Reino Unido',
    verified: true,
    featuredTrackTitle: 'Bohemian Rhapsody',
    topAlbums: ['A Night at the Opera', 'News of the World', 'The Game', 'Jazz'],
  },
};

export const AUTHENTIC_ALBUMS: Record<string, AuthenticAlbumInfo> = {
  // Matuê
  maquina_do_tempo: {
    id: 'maquina_do_tempo',
    title: 'Máquina do Tempo',
    normalizedTitles: ['maquina do tempo', 'maquina do tempo matue', 'maquinadotempo'],
    artistName: 'Matuê',
    coverUrl: 'https://cdn-images.dzcdn.net/images/cover/9ad06bcb9f0bfe52bbd5e6ff464e4ca4/1000x1000-000000-80-0-0.jpg',
    releaseYear: 2020,
    label: '30PRAUM / Sony Music',
    genre: 'Trap Brasil',
    totalTracks: 7,
    hiResBadge: 'Master 24b / 48kHz',
  },

  matue_333: {
    id: 'matue_333',
    title: '333',
    normalizedTitles: ['333', '333 matue'],
    artistName: 'Matuê',
    coverUrl: 'https://cdn-images.dzcdn.net/images/cover/a4d8ede7aecd45c9e4b4858487a02a88/1000x1000-000000-80-0-0.jpg',
    releaseYear: 2024,
    label: '30PRAUM',
    genre: 'Trap Brasil',
    totalTracks: 12,
    hiResBadge: 'Master 24b / 96kHz',
  },

  // The Weeknd
  after_hours: {
    id: 'after_hours',
    title: 'After Hours',
    normalizedTitles: ['after hours', 'after hours the weeknd', 'afterhours'],
    artistName: 'The Weeknd',
    coverUrl: 'https://cdn-images.dzcdn.net/images/cover/f520bf0be2e3cfc476824e75d20a164a/1000x1000-000000-80-0-0.jpg',
    releaseYear: 2020,
    label: 'XO / Republic Records',
    genre: 'R&B / Synthwave',
    totalTracks: 14,
    hiResBadge: 'Spatial Audio 24b',
  },

  starboy: {
    id: 'starboy',
    title: 'Starboy',
    normalizedTitles: ['starboy', 'starboy the weeknd', 'starboy album'],
    artistName: 'The Weeknd',
    coverUrl: 'https://cdn-images.dzcdn.net/images/cover/134778e4c4f19ea71c82408300925a9a/1000x1000-000000-80-0-0.jpg',
    releaseYear: 2016,
    label: 'XO / Republic Records',
    genre: 'R&B / Electro-Pop',
    totalTracks: 18,
    hiResBadge: 'Master 24b / 44.1kHz',
  },

  dawn_fm: {
    id: 'dawn_fm',
    title: 'Dawn FM',
    normalizedTitles: ['dawn fm', 'dawn fm the weeknd', 'dawnfm'],
    artistName: 'The Weeknd',
    coverUrl: 'https://cdn-images.dzcdn.net/images/cover/a2bad973a4002e46109ff36b91fbcfd7/1000x1000-000000-80-0-0.jpg',
    releaseYear: 2022,
    label: 'XO / Republic Records',
    genre: 'Synth-Pop / Dance',
    totalTracks: 16,
    hiResBadge: 'Spatial Audio 24b',
  },

  // BK'
  icarus: {
    id: 'icarus',
    title: 'ICARUS',
    normalizedTitles: ['icarus', 'icarus bk', 'icarus bk’'],
    artistName: "BK'",
    coverUrl: 'https://cdn-images.dzcdn.net/images/cover/927397ea14b00eba92454a88ec4f352d/1000x1000-000000-80-0-0.jpg',
    releaseYear: 2022,
    label: 'Gigantes / Altafonte',
    genre: 'Rap Nacional',
    totalTracks: 13,
    hiResBadge: 'Hi-Res Lossless',
  },

  castelos_e_ruinas: {
    id: 'castelos_e_ruinas',
    title: 'Castelos & Ruínas',
    normalizedTitles: ['castelos & ruinas', 'castelos e ruinas', 'castelos e ruinas bk', 'castelosruinas'],
    artistName: "BK'",
    coverUrl: 'https://cdn-images.dzcdn.net/images/cover/3bf2d1550ca05efe0f81e74a4c3ab36a/1000x1000-000000-80-0-0.jpg',
    releaseYear: 2016,
    label: 'Pirâmide Perdida',
    genre: 'Rap Nacional',
    totalTracks: 13,
    hiResBadge: 'Studio Master 24b',
  },

  gigantes: {
    id: 'gigantes',
    title: 'Gigantes',
    normalizedTitles: ['gigantes', 'gigantes bk', 'album gigantes'],
    artistName: "BK'",
    coverUrl: 'https://cdn-images.dzcdn.net/images/cover/13103383613a315ede506b364b8f5e51/1000x1000-000000-80-0-0.jpg',
    releaseYear: 2018,
    label: 'Pirâmide Perdida',
    genre: 'Rap Nacional',
    totalTracks: 12,
    hiResBadge: 'Master 24b',
  },

  // Dua Lipa
  future_nostalgia: {
    id: 'future_nostalgia',
    title: 'Future Nostalgia',
    normalizedTitles: ['future nostalgia', 'future nostalgia dua lipa', 'futurenostalgia'],
    artistName: 'Dua Lipa',
    coverUrl: 'https://cdn-images.dzcdn.net/images/cover/f8364f090ba04f1b19b381ec0390f3e4/1000x1000-000000-80-0-0.jpg',
    releaseYear: 2020,
    label: 'Warner Records',
    genre: 'Nu-Disco / Pop',
    totalTracks: 11,
    hiResBadge: 'Spatial Audio 24b / 96kHz',
  },

  radical_optimism: {
    id: 'radical_optimism',
    title: 'Radical Optimism',
    normalizedTitles: ['radical optimism', 'radical optimism dua lipa', 'radicaloptimism'],
    artistName: 'Dua Lipa',
    coverUrl: 'https://cdn-images.dzcdn.net/images/cover/e77de425a3ba0c69f00e6525daec5738/1000x1000-000000-80-0-0.jpg',
    releaseYear: 2024,
    label: 'Warner Records',
    genre: 'Pop Psicodélico / Dance',
    totalTracks: 11,
    hiResBadge: 'Spatial Audio 24b / 96kHz',
  },

  // Djonga
  ladrao: {
    id: 'ladrao',
    title: 'Ladrão',
    normalizedTitles: ['ladrao', 'ladrao djonga', 'ladrão'],
    artistName: 'Djonga',
    coverUrl: 'https://cdn-images.dzcdn.net/images/cover/55df905d05d2c226a17cc6ff163204dd/1000x1000-000000-80-0-0.jpg',
    releaseYear: 2019,
    label: 'Ceia Ent. / A Quadrilha',
    genre: 'Rap Nacional',
    totalTracks: 10,
    hiResBadge: 'Studio Master 24b',
  },

  heresia: {
    id: 'heresia',
    title: 'Heresia',
    normalizedTitles: ['heresia', 'heresia djonga'],
    artistName: 'Djonga',
    coverUrl: 'https://cdn-images.dzcdn.net/images/cover/8c61c365b4e658a1131100a4d9b5f389/1000x1000-000000-80-0-0.jpg',
    releaseYear: 2017,
    label: 'Ceia Ent.',
    genre: 'Rap Nacional',
    totalTracks: 10,
    hiResBadge: 'Master 24b',
  },

  o_menino_que_queria_ser_deus: {
    id: 'o_menino_que_queria_ser_deus',
    title: 'O Menino que Queria Ser Deus',
    normalizedTitles: ['o menino que queria ser deus', 'o menino que queria ser deus djonga', 'menino que queria ser deus'],
    artistName: 'Djonga',
    coverUrl: 'https://cdn-images.dzcdn.net/images/cover/10ba01b01c2e8517166d7f2270a7d454/1000x1000-000000-80-0-0.jpg',
    releaseYear: 2018,
    label: 'Ceia Ent.',
    genre: 'Rap Nacional',
    totalTracks: 10,
    hiResBadge: 'Master 24b',
  },

  // Sabotage
  rap_e_compromisso: {
    id: 'rap_e_compromisso',
    title: 'Rap É Compromisso',
    normalizedTitles: ['rap e compromisso', 'rap e compromisso sabotage', 'rap é compromisso'],
    artistName: 'Sabotage',
    coverUrl: 'https://cdn-images.dzcdn.net/images/cover/d9801848020a195308a0b2de9da074ff/1000x1000-000000-80-0-0.jpg',
    releaseYear: 2000,
    label: 'Cosa Nostra / Som Brasil',
    genre: 'Rap Nacional Clássico',
    totalTracks: 11,
    hiResBadge: 'Remaster 24b / 96kHz',
  },

  // Racionais MC's
  nada_como_um_dia: {
    id: 'nada_como_um_dia',
    title: 'Nada como um Dia após o Outro Dia',
    normalizedTitles: ['nada como um dia apos o outro dia', 'nada como um dia', 'nada como um dia racionais'],
    artistName: "Racionais MC's",
    coverUrl: 'https://cdn-images.dzcdn.net/images/cover/e04b68c5a1aa7a29128d05e7ff9e3084/1000x1000-000000-80-0-0.jpg',
    releaseYear: 2002,
    label: 'Cosa Nostra Fonográfica',
    genre: 'Rap Nacional',
    totalTracks: 21,
    hiResBadge: 'Master Duplo 24b',
  },

  sobrevivendo_no_inferno: {
    id: 'sobrevivendo_no_inferno',
    title: 'Sobrevivendo no Inferno',
    normalizedTitles: ['sobrevivendo no inferno', 'sobrevivendo no inferno racionais'],
    artistName: "Racionais MC's",
    coverUrl: 'https://cdn-images.dzcdn.net/images/cover/bc55cb71a6da7f0c41f1dc184280fe32/1000x1000-000000-80-0-0.jpg',
    releaseYear: 1997,
    label: 'Cosa Nostra Fonográfica',
    genre: 'Rap Nacional',
    totalTracks: 12,
    hiResBadge: 'Patrimônio Nacional 24b',
  },

  // Criolo
  no_na_orelha: {
    id: 'no_na_orelha',
    title: 'Nó na Orelha',
    normalizedTitles: ['no na orelha', 'no na orelha criolo', 'nó na orelha'],
    artistName: 'Criolo',
    coverUrl: 'https://cdn-images.dzcdn.net/images/cover/756d8d0262d22eb39099448293dfe323/1000x1000-000000-80-0-0.jpg',
    releaseYear: 2011,
    label: 'Oloko Records',
    genre: 'MPB / Rap / Samba',
    totalTracks: 10,
    hiResBadge: 'Audiophile Master 24b',
  },

  // Daft Punk
  random_access_memories: {
    id: 'random_access_memories',
    title: 'Random Access Memories',
    normalizedTitles: ['random access memories', 'random access memories daft punk', 'ram daft punk', 'randomaccessmemories'],
    artistName: 'Daft Punk',
    coverUrl: 'https://cdn-images.dzcdn.net/images/cover/311bba0fc112d15f72c8b5a65f0456c1/1000x1000-000000-80-0-0.jpg',
    releaseYear: 2013,
    label: 'Columbia / Daft Life',
    genre: 'Disco / Funk / Electronic',
    totalTracks: 13,
    hiResBadge: 'Studio Master 24b / 88.2kHz',
  },

  discovery: {
    id: 'discovery',
    title: 'Discovery',
    normalizedTitles: ['discovery', 'discovery daft punk', 'discovery album'],
    artistName: 'Daft Punk',
    coverUrl: 'https://cdn-images.dzcdn.net/images/cover/5718f7c81c27e0b2417e2a4c45224f8a/1000x1000-000000-80-0-0.jpg',
    releaseYear: 2001,
    label: 'Virgin / Daft Life',
    genre: 'French House / Synth',
    totalTracks: 14,
    hiResBadge: 'Master 24b / 96kHz',
  },

  // Frank Ocean
  blonde: {
    id: 'blonde',
    title: 'Blonde',
    normalizedTitles: ['blonde', 'blonde frank ocean'],
    artistName: 'Frank Ocean',
    coverUrl: 'https://cdn-images.dzcdn.net/images/cover/aa7e6de00b0810f5051aa60b489f58d8/1000x1000-000000-80-0-0.jpg',
    releaseYear: 2016,
    label: 'Boys Don\'t Cry',
    genre: 'Alternative R&B',
    totalTracks: 17,
    hiResBadge: 'Master Lossless',
  },

  channel_orange: {
    id: 'channel_orange',
    title: 'Channel Orange',
    normalizedTitles: ['channel orange', 'channel orange frank ocean'],
    artistName: 'Frank Ocean',
    coverUrl: 'https://cdn-images.dzcdn.net/images/cover/519400e29d268f449cf00af879e71af6/1000x1000-000000-80-0-0.jpg',
    releaseYear: 2012,
    label: 'Def Jam',
    genre: 'Neo-Soul / R&B',
    totalTracks: 17,
    hiResBadge: 'Hi-Res 24b',
  },

  // WIU & Veigh & Filipe Ret
  manual_de_como_amar_errado: {
    id: 'manual_de_como_amar_errado',
    title: 'Manual de Como Amar Errado',
    normalizedTitles: ['manual de como amar errado', 'manual de como amar errado wiu'],
    artistName: 'WIU',
    coverUrl: 'https://cdn-images.dzcdn.net/images/cover/b07091e5372393f45e20d4ec7ff808d4/1000x1000-000000-80-0-0.jpg',
    releaseYear: 2022,
    label: '30PRAUM',
    genre: 'Trap / R&B',
    totalTracks: 10,
    hiResBadge: 'Master 24b',
  },

  dos_predios_deluxe: {
    id: 'dos_predios_deluxe',
    title: 'Dos Prédios Deluxe',
    normalizedTitles: ['dos predios deluxe', 'dos predios deluxe veigh', 'dos predios'],
    artistName: 'Veigh',
    coverUrl: 'https://cdn-images.dzcdn.net/images/cover/b300e05a1b78466f15c81677e4ba33d9/1000x1000-000000-80-0-0.jpg',
    releaseYear: 2023,
    label: 'Supernova Ent.',
    genre: 'Trap Brasil',
    totalTracks: 19,
    hiResBadge: 'Master 24b',
  },

  filipe_ret_lume: {
    id: 'filipe_ret_lume',
    title: 'LUME',
    normalizedTitles: ['lume', 'lume filipe ret', 'lume ret'],
    artistName: 'Filipe Ret',
    coverUrl: 'https://cdn-images.dzcdn.net/images/cover/966c622d2a432a7bffff340ef36836c7/1000x1000-000000-80-0-0.jpg',
    releaseYear: 2022,
    label: 'NadaMal / Som Livre',
    genre: 'Trap Brasil',
    totalTracks: 11,
    hiResBadge: 'Master 24b',
  },

  // Travis Scott & Kendrick & Billie
  utopia: {
    id: 'utopia',
    title: 'UTOPIA',
    normalizedTitles: ['utopia', 'utopia travis scott', 'utopia album'],
    artistName: 'Travis Scott',
    coverUrl: 'https://cdn-images.dzcdn.net/images/cover/6c91e64b7157f1332a4f6b0de9e4c714/1000x1000-000000-80-0-0.jpg',
    releaseYear: 2023,
    label: 'Cactus Jack / Epic Records',
    genre: 'Hip-Hop / Trap',
    totalTracks: 19,
    hiResBadge: 'Spatial Audio 24b',
  },

  astroworld: {
    id: 'astroworld',
    title: 'ASTROWORLD',
    normalizedTitles: ['astroworld', 'astroworld travis scott'],
    artistName: 'Travis Scott',
    coverUrl: 'https://cdn-images.dzcdn.net/images/cover/7df7ac6028591a5622f24cf32a555510/1000x1000-000000-80-0-0.jpg',
    releaseYear: 2018,
    label: 'Cactus Jack / Grand Hustle',
    genre: 'Trap / Psicodélico',
    totalTracks: 17,
    hiResBadge: 'Master 24b',
  },

  kendrick_damn: {
    id: 'kendrick_damn',
    title: 'DAMN.',
    normalizedTitles: ['damn', 'damn.', 'damn kendrick lamar'],
    artistName: 'Kendrick Lamar',
    coverUrl: 'https://cdn-images.dzcdn.net/images/cover/7ce6b8452fae425557067db6e6a1cad5/1000x1000-000000-80-0-0.jpg',
    releaseYear: 2017,
    label: 'Top Dawg / Aftermath',
    genre: 'Hip-Hop',
    totalTracks: 14,
    hiResBadge: 'Master 24b / 96kHz',
  },

  billie_hit_me_hard_and_soft: {
    id: 'billie_hit_me_hard_and_soft',
    title: 'HIT ME HARD AND SOFT',
    normalizedTitles: ['hit me hard and soft', 'hit me hard and soft billie eilish'],
    artistName: 'Billie Eilish',
    coverUrl: 'https://cdn-images.dzcdn.net/images/cover/5d284b31cb9ddeb1a0c79aede5a94e1c/1000x1000-000000-80-0-0.jpg',
    releaseYear: 2024,
    label: 'Darkroom / Interscope Records',
    genre: 'Alt-Pop',
    totalTracks: 10,
    hiResBadge: 'Spatial Audio 24b / 48kHz',
  },

  // Arctic Monkeys & Tame Impala
  arctic_monkeys_am: {
    id: 'arctic_monkeys_am',
    title: 'AM',
    normalizedTitles: ['am', 'am arctic monkeys', 'album am'],
    artistName: 'Arctic Monkeys',
    coverUrl: 'https://cdn-images.dzcdn.net/images/cover/64e54e307bd5e2bdb27ffeb662fd910d/1000x1000-000000-80-0-0.jpg',
    releaseYear: 2013,
    label: 'Domino Recording Co.',
    genre: 'Indie Rock',
    totalTracks: 12,
    hiResBadge: 'Studio Master 24b / 44.1kHz',
  },

  tame_impala_currents: {
    id: 'tame_impala_currents',
    title: 'Currents',
    normalizedTitles: ['currents', 'currents tame impala', 'currents album'],
    artistName: 'Tame Impala',
    coverUrl: 'https://cdn-images.dzcdn.net/images/cover/de5b9b704cd4ec36f8bf49beb3e17ba2/1000x1000-000000-80-0-0.jpg',
    releaseYear: 2015,
    label: 'Modular / Interscope',
    genre: 'Psychedelic Pop',
    totalTracks: 13,
    hiResBadge: 'Master 24b / 44.1kHz',
  },
};
